# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 19:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('qualification', '0001_initial'),
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('course_organiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.Faculty')),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.Pathway')),
            ],
        ),
        migrations.CreateModel(
            name='CourseStudent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_grade', models.CharField(blank=True, max_length=6, null=True)),
                ('predicted_grade', models.CharField(blank=True, max_length=6, null=True)),
                ('target_grade', models.CharField(blank=True, max_length=6, null=True)),
                ('final_ucas_points', models.IntegerField(blank=True, null=True)),
                ('predicted_ucas_points', models.IntegerField(blank=True, null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('students', models.ManyToManyField(related_name='group_students', to=settings.AUTH_USER_MODEL)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(related_name='course_students', through='course.CourseStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='subject_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.SubjectSector'),
        ),
        migrations.AddField(
            model_name='course',
            name='units',
            field=models.ManyToManyField(to='qualification.PathwayUnit'),
        ),
    ]
