# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-24 19:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway', models.CharField(blank=True, max_length=50, null=True)),
                ('mandatory_credits', models.IntegerField()),
                ('optional_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PathwayUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_override', models.IntegerField(blank=True, null=True)),
                ('mandatory', models.BooleanField()),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.Pathway')),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=10, unique=True, verbose_name='qualification number')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField(choices=[(2, 'Level 2'), (3, 'Level 3')], default=3)),
                ('glh', models.IntegerField(verbose_name='guided learning hours')),
                ('framework', models.CharField(choices=[('QCF', 'Qualifications and Credit Framework'), ('NQF', 'National Qualification Framework')], max_length=3)),
                ('total_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QualificationGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=6)),
                ('full_grade', models.CharField(max_length=50)),
                ('points_start', models.IntegerField()),
                ('points_end', models.IntegerField(blank=True, null=True)),
                ('ucas_points', models.IntegerField(blank=True, null=True)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('glh', models.IntegerField()),
                ('level', models.IntegerField()),
                ('subject_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.SubjectSector')),
            ],
        ),
        migrations.AddField(
            model_name='pathwayunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.Unit'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='qualification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.Qualification'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='subject_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.SubjectSector'),
        ),
        migrations.AddField(
            model_name='pathway',
            name='units',
            field=models.ManyToManyField(through='qualification.PathwayUnit', to='qualification.Unit'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='qualificationgrade',
            unique_together=set([('qualification', 'grade')]),
        ),
        migrations.AlterUniqueTogether(
            name='pathwayunit',
            unique_together=set([('pathway', 'unit')]),
        ),
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together=set([('unit', 'number')]),
        ),
    ]
