# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-16 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Criteria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=3)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Qualification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qn', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=50)),
                ('pathway', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('glh', models.IntegerField()),
                ('total_credits', models.IntegerField()),
                ('mandatory_credits', models.IntegerField()),
                ('optional_credits', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='QualificationGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=6)),
                ('description', models.CharField(max_length=50)),
                ('points_start', models.IntegerField()),
                ('points_end', models.IntegerField(blank=True, null=True)),
                ('ucas_points', models.IntegerField(blank=True, null=True)),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='QualificationUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('mandatory', models.BooleanField()),
                ('qualification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.Qualification')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('credits', models.IntegerField()),
                ('glh', models.IntegerField()),
                ('level', models.IntegerField()),
                ('subject_sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='misc.SubjectSector')),
            ],
        ),
        migrations.AddField(
            model_name='qualificationunit',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.Unit'),
        ),
        migrations.AddField(
            model_name='qualification',
            name='units',
            field=models.ManyToManyField(through='qualification.QualificationUnit', to='qualification.Unit'),
        ),
        migrations.AddField(
            model_name='criteria',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='qualification.Unit'),
        ),
        migrations.AlterUniqueTogether(
            name='qualificationunit',
            unique_together=set([('qualification', 'unit', 'number')]),
        ),
        migrations.AlterUniqueTogether(
            name='qualificationgrade',
            unique_together=set([('qualification', 'grade')]),
        ),
        migrations.AlterUniqueTogether(
            name='qualification',
            unique_together=set([('qn', 'pathway')]),
        ),
        migrations.AlterUniqueTogether(
            name='criteria',
            unique_together=set([('unit', 'number')]),
        ),
    ]
