# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-18 00:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qualification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='glh',
            field=models.IntegerField(verbose_name='guided learning hours'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='level',
            field=models.IntegerField(choices=[(2, 'Level 2'), (3, 'Level 3')], default=3),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='pathway',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='qn',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_qn', message='Invalid qualification number. Must follow F/3495/239 example.', regex='([A-Z])\\/([0-9]){4}\\/([0-9]){3}')], verbose_name='qualification number'),
        ),
        migrations.AlterField(
            model_name='qualification',
            name='total_credits',
            field=models.IntegerField(validators=['validate_total_credits']),
        ),
    ]
